# https://github.com/perseusrealdeal/TestHound/blob/master/.swiftlint.yml

included:
  - Kompas.id
excluded:
  - Pods
  - get-pip.py
  - Kompas.id/Helpers/Cryptor/
  - Kompas.id/App/KompasIdApp.swift


disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - vertical_whitespace
  - trailing_newline
  - todo
  - orphaned_doc_comment
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - void_function_in_ternary
  - switch_case_alignment
  - for_where
  - implicit_getter
  - trailing_comma
  - shorthand_operator
  - unused_enumerated
  - class_delegate_protocol
  - mark
  - closure_parameter_position
  - legacy_hashing

  - line_length
  - type_body_length
  - function_body_length
  - file_length
  - large_tuple
  - function_parameter_count
  - type_name
  - identifier_name

# line_length: 1000

# type_body_length:
#   - 900 # warning
#   - 1000 # error
  
# function_body_length:
#   - 700 # warning
#   - 1000 # error
  
# file_length:
#   - 1500 # warning
#   - 2000 # error

# large_tuple:
#   - 5 # warning
#   - 7 # error

# function_parameter_count:
#   - 9

# type_name:
#   min_length: 1 # only min_length
#   max_length: 60
  
# identifier_name:
#   min_length: 2 # only min_length
#   max_length: 50
#   excluded: # excluded via string array
#     - id
#     - URL


